# Generated by Django 4.2.8 on 2024-01-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=-2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='9-7-2023', upload_to='todoimage'),
            preserve_default=False,
        ),
    ]
